import type { Brand } from "@/types";

/**
 * 브랜드 목록
 * - 단종/비활성 브랜드는 배열에서 삭제하지 않고 isActive=false로 처리한다.
 * - 화면에 브랜드 개수를 표시할 때는 brands.filter(b => b.isActive).length 사용.
 *   절대 숫자를 하드코딩하지 않는다.
 */
export const brands: Brand[] = [
  {
    slug: "benekid",
    name: "베네키드",
    nameEn: "BeneKid",
    category: "TODO",
    tagline: "여덟 살과 열네 살, 필요한 건 다릅니다",
    story: ["몸이 가장 빠르게 변하는 시기, 그때마다 달라지는 영양이 있습니다. 베네키드는 시기마다의 답을 만듭니다."],
    heroImage: "/images/brands/benekid-hero.jpg",
    cardImage: "/images/brands/benekid-card.jpg",
    storeUrl: "https://benekid.kr",
    isActive: true,
  },
  {
    slug: "dailyplan",
    name: "데일리플랜",
    nameEn: "DailyPlan",
    category: "TODO",
    tagline: "오늘 하나, 내일 또 하나",
    story: ["챙긴 하루가 쌓여 아이의 키가 됩니다. 데일리플랜은 자연에서 온 원료로 그 하루를 채웁니다."],
    heroImage: "/images/brands/dailyplan-hero.jpg",
    cardImage: "/images/brands/dailyplan-card.jpg",
    storeUrl: "https://dailyplan.kr",
    isActive: true,
  },
  {
    slug: "dewora",
    name: "듀오라",
    nameEn: "Dewora",
    category: "TODO",
    tagline: "사막에서도 마르지 않는 이유",
    story: [
      "메마른 사막에서도 생명은 스스로 수분을 지켜냅니다.",
      "DEWORA는 그 놀라운 생명력에서 보습의 본질을 바라보았습니다.",
      "극한의 건조 환경에서도 수분을 보호하는 성분, 트레할로오스.",
      "쉽게 증발하지 않고 오래 머무는 수분의 힘을 피부에 담아,",
      "DEWORA는 건조함에 흔들리지 않는 보습의 답을 제안합니다.",
    ],
    heroImage: "/images/brands/dewora_hero.jpg",
    cardImage: "/images/brands/dewora-card.jpg",
    storeUrl: "https://example.com/store-dewora",
    // TODO: 실제 제품 이미지/링크로 교체
    products: [
      { image: "/images/brands/dewora_prod_1.jpg", link: "https://example.com/store-dewora/product-1" },
      { image: "/images/brands/dewora_prod_2.jpg", link: "https://example.com/store-dewora/product-2" },
      { image: "/images/brands/dewora_prod_3.jpg", link: "https://example.com/store-dewora/product-3" },
    ],
    isActive: true,
  },
  {
    slug: "dodit",
    name: "두디트",
    nameEn: "DoDit",
    category: "TODO",
    tagline: "여성들의 다이어트 파트너",
    story: [
      "다이어트는 혼자 버티는 싸움이 아니라, 누군가와 함께할 때 더 오래 갈 수 있는 여정이에요.",
      "두디트는 그 길 위에서 여성들의 곁을 지키는 다이어트 파트너가 되고 싶었습니다.",
      "그래서 무작정 참고 줄이기보다, 맛있게 먹으면서도 가볍게 이어갈 수 있는 방법을 고민했고",
      "바쁜 하루 속에서도 부담 없이 챙길 수 있도록 맛과 편리함을 함께 담았어요.",
      "숫자보다 나 자신에게 집중하는 매일, 두디트가 그 변화의 시작을 함께할게요.",
    ],
    heroImage: "/images/brands/dodit_hero.jpg",
    cardImage: "/images/brands/dodit-card.jpg",
    storeUrl: "https://dodit.kr/diet",
    products: [
      { image: "/images/brands/dodit_prod_1.jpg", link: "https://dodit.kr/diet/?idx=14" },
      { image: "/images/brands/dodit_prod_2.jpg", link: "https://dodit.kr/diet/?idx=6" },
    ],
    isActive: true,
  },
  {
    slug: "kidzdam",
    name: "키즈담",
    nameEn: "KiDZ:DAM",
    category: "TODO",
    tagline: "아이의 오늘을 채우고, 내일의 성장을 담다",
    story: [
      "키즈담은 성장기 아이들에게 필요한 영양을 고민하는 키즈 헬스케어 브랜드입니다.",
      "아이들의 건강한 성장과 균형 잡힌 영양, 그리고 학습과 일상에 필요한 영양 관리까지 생각합니다.",
      "하루하루 자라나는 아이들에게 필요한 것은 단순히 많은 영양이 아니라,",
      " 성장 시기에 맞는 올바른 영양의 균형이라고 믿습니다.",
      "키즈담은 아이의 키 성장부터 두뇌 건강까지, 부모가 안심하고 선택할 수 있는 제품을 연구하고 제안합니다.",
      "아이의 가능성이 더 크게 자랄 수 있도록, 성장에 필요한 좋은 것들을 차곡차곡 담습니다.",
    ],
    heroImage: "/images/brands/kidzdam_hero.jpg",
    cardImage: "/images/brands/kidzdam-card.jpg",
    storeUrl: "https://kidzdam.kr/products",
      products: [
      { image: "/images/brands/kidzdam_prod_1.jpg", link: "https://kidzdam.kr/products/?idx=4" },
      { image: "/images/brands/kidzdam_prod_2.jpg", link: "https://kidzdam.kr/products/?idx=6" },
    ],
    isActive: true,
  },
  {
    slug: "kidzplan",
    name: "키즈플랜",
    nameEn: "KIDZPLAN",
    category: "TODO",
    tagline: "아이의 성장을 위한 더 나은 기준, 키즈플랜",
    story: [
      "키즈플랜은 아이의 건강한 성장과 쾌적한 일상을 함께 고민하는 프리미엄 키즈 라이프케어 브랜드입니다.",
      "성장기 아이를 위한 영양 관리부터 아이와 함께하는 생활 공간까지,",
      "일상에 필요한 제품을 세심하게 제안합니다.",
      "성분과 품질을 꼼꼼하게 살피며 부모가 믿고 선택할 수 있는 기준을 만들어갑니다.",
      "건강하게 자라는 시간, 키즈플랜이 함께합니다.",
    ],
    heroImage: "/images/brands/kidzplan_hero.jpg",
    cardImage: "/images/brands/kidzplan-card.jpg",
    storeUrl: "https://kidzplan.kr",
    products: [
      { image: "/images/brands/kidzplan_prod_1.jpg", link: "https://kidzplan.kr/15/?idx=1" },
      { image: "/images/brands/kidzplan_prod_2.jpg", link: "https://kidzplan.kr/15/?idx=11" },
    ],
    isActive: true,
  },
  {
    slug: "livature",
    name: "리브어쳐",
    nameEn: "Livature",
    category: "TODO",
    tagline: "머리카락은 두피에서 시작합니다",
    story: ["겉으로 보이는 모발보다 뿌리가 먼저입니다. 리브어쳐는 두피부터 채웁니다."],
    heroImage: "/images/brands/livature-hero.jpg",
    cardImage: "/images/brands/livature-card.jpg",
    storeUrl: "https://example.com/store-livature",
    isActive: true,
  },
  {
    slug: "livderm",
    name: "리브덤",
    nameEn: "LIVDERM",
    category: "TODO",
    tagline: "필요한 곳에, 필요한 만큼",
    story: ["관절에는 타마누의 진정을, 눈가에는 노화를 늦추는 힘을. 리브덤은 부위마다 다른 답을 준비합니다."],
    heroImage: "/images/brands/livderm-hero.jpg",
    cardImage: "/images/brands/livderm-card.jpg",
    storeUrl: "https://livderm.kr",
    isActive: true,
  },
  {
    slug: "moyoku",
    name: "모요쿠",
    nameEn: "MOYOKU",
    category: "TODO",
    tagline: "씻는 시간이 아니라 쉬는 시간입니다",
    story: ["일본의 목욕 루틴에서 시작했습니다. 물에 몸을 담그는 동안, 하루의 무게가 조금 가벼워집니다."],
    heroImage: "/images/brands/moyoku-hero.jpg",
    cardImage: "/images/brands/moyoku-card.jpg",
    storeUrl: "https://moyoku.kr/",
    isActive: true,
  },
  {
    slug: "oroshe",
    name: "오로쉬",
    nameEn: "Oroshe",
    category: "TODO",
    tagline: "에스트로겐 리그난 한 알",
    story: ["여성의 몸은 시기마다 다른 것을 필요로 합니다. 오로쉬는 지금 필요한 한 알을 만듭니다."],
    heroImage: "/images/brands/oroshe-hero.jpg",
    cardImage: "/images/brands/oroshe-card.jpg",
    storeUrl: "https://oroshe.kr",
    instagramUrl: "https://instagram.com/oroshe",
    isActive: true,
  },
  {
    slug: "planlight",
    name: "플랜라이트",
    nameEn: "Planlight",
    category: "TODO",
    tagline: "가볍게 만드는 일에 집중합니다",
    story: ["무거운 하루를 덜어내는 것, 그거 하나면 충분합니다. 스웰컷으로 플랜라이트가 합니다."],
    heroImage: "/images/brands/planlight-hero.jpg",
    cardImage: "/images/brands/planlight-card.jpg",
    storeUrl: "https://example.com/store-planlight",
    isActive: true,
  },
  {
    slug: "brand-c",
    name: "TODO: 브랜드C 이름",
    nameEn: "TODO: Brand C",
    category: "TODO",
    tagline: "TODO: 태그라인",
    story: ["TODO: 브랜드 스토리"],
    heroImage: "/images/brands/brand-c-hero.jpg",
    cardImage: "/images/brands/brand-c-card.jpg",
    storeUrl: "https://example.com/store-c",
    isActive: false,
  },
];
