import type { Brand } from "@/types";

/**
 * 브랜드 목록
 * - 단종/비활성 브랜드는 배열에서 삭제하지 않고 isActive=false로 처리한다.
 * - 화면에 브랜드 개수를 표시할 때는 brands.filter(b => b.isActive).length 사용.
 *   절대 숫자를 하드코딩하지 않는다.
 */
export const brands: Brand[] = [
  {
    slug: "benekid",
    name: "베네키드",
    nameEn: "BeneKid",
    category: "TODO",
    tagline: "아이의 빛나는 성장을 위해 \n매일의 건강을 섬세하게 채우는 베네키드.",
    story: [
      "아이의 하루는 매일 조금씩 자라납니다. 베네키드는 그 소중한 변화의 순간을 세심하게 바라봅니다.",
      "좋은 것만 전하고 싶은 부모의 마음을 담아 건강한 성장과 편안한 일상을 위한 기준을 고민합니다.",
      "아이의 오늘이 더 빛나는 내일로 이어지도록 함께합니다.",
    ],
    heroImage: "/images/brands/benekid_hero.jpg",
    cardImage: "/images/brands/benekid-card.jpg",
    storeUrl: "https://benekid.kr",
    products: [
      { image: "/images/brands/benekid_prod_1.jpg", link: "https://benekid.kr/all/?idx=11" },
      { image: "/images/brands/benekid_prod_2.jpg", link: "https://benekid.kr/all/?idx=2" },
    ],
    isActive: true, 
  },
  {
    slug: "dailyplan",
    name: "데일리플랜",
    nameEn: "DailyPlan",
    category: "TODO",
    tagline: "아이의 건강한 성장을 함께 설계하는 \n프리미엄 키즈 브랜드, 데일리플랜.",
    story: [
      "데일리플랜은 성장기 아이들의 건강한 일상을 연구합니다.",
      "키 성장부터 눈 건강까지, 매일 필요한 영양과 케어를 균형 있게 제안합니다.",
      "아이에게는 꾸준한 건강 습관을, 부모에게는 믿고 선택할 수 있는 기준을 만듭니다.",
    ],
    heroImage: "/images/brands/dailyplan_hero.jpg",
    cardImage: "/images/brands/dailyplan-card.jpg",
    storeUrl: "https://dailyplan.kr",
    products: [
      { image: "/images/brands/dailyplan_prod_1.jpg", link: "https://dailyplan.kr/all/?idx=7" },
      { image: "/images/brands/dailyplan_prod_2.jpg", link: "https://dailyplan.kr/all/?idx=1" },
      { image: "/images/brands/dailyplan_prod_3.jpg", link: "https://dailyplan.kr/all/?idx=2" },
    ],
    isActive: true,
  },
  {
    slug: "dewora",
    name: "듀오라",
    nameEn: "Dewora",
    category: "TODO",
    tagline: "사막에서 찾은 수분 저장의 힘",
    story: [
      "메마른 사막에서도 생명은 스스로 수분을 지켜냅니다.",
      "DEWORA는 그 놀라운 생명력에서 보습의 본질을 바라보았습니다.",
      "극한의 건조 환경에서도 수분을 보호하는 성분, 트레할로오스.",
      "쉽게 증발하지 않고 오래 머무는 수분의 힘을 피부에 담아,",
      "DEWORA는 건조함에 흔들리지 않는 보습의 답을 제안합니다.",
    ],
    heroImage: "/images/brands/dewora_hero.jpg",
    cardImage: "/images/brands/dewora-card.jpg",
    storeUrl: "https://dewora.kr/",
    products: [
      { image: "/images/brands/dewora_prod_1.jpg", link: "https://dewora.kr/shop_view/?idx=3" },
      { image: "/images/brands/dewora_prod_2.jpg", link: "https://dewora.kr/shop_view/?idx=6" },
      { image: "/images/brands/dewora_prod_3.jpg", link: "https://dewora.kr/shop_view/?idx=4" },
    ],
    isActive: true,
  },
  {
    slug: "dodit",
    name: "두디트",
    nameEn: "DoDit",
    category: "TODO",
    tagline: "여성들의 다이어트 파트너",
    story: [
      "다이어트는 혼자 버티는 싸움이 아니라, 누군가와 함께할 때 더 오래 갈 수 있는 여정이에요.",
      "두디트는 그 길 위에서 여성들의 곁을 지키는 다이어트 파트너가 되고 싶었습니다.",
      "그래서 무작정 참고 줄이기보다, 맛있게 먹으면서도 가볍게 이어갈 수 있는 방법을 고민했고",
      "바쁜 하루 속에서도 부담 없이 챙길 수 있도록 맛과 편리함을 함께 담았어요.",
      "숫자보다 나 자신에게 집중하는 매일, 두디트가 그 변화의 시작을 함께할게요.",
    ],
    heroImage: "/images/brands/dodit_hero.jpg",
    cardImage: "/images/brands/dodit-card.jpg",
    storeUrl: "https://dodit.kr/diet",
    products: [
      { image: "/images/brands/dodit_prod_1.jpg", link: "https://dodit.kr/diet/?idx=14" },
      { image: "/images/brands/dodit_prod_2.jpg", link: "https://dodit.kr/diet/?idx=6" },
    ],
    isActive: true,
  },
    {
    slug: "drbite",
    name: "닥터바이트",
    nameEn: "DR.BITE",
    category: "TODO",
    tagline: "미국에서 생산된 고품질 구강 건강 브랜드, 닥터바이트",
    story: [
      "닥터바이트는 미국에서 생산되는 프리미엄 구강 건강 브랜드입니다.",
      "높은 품질 기준을 바탕으로 일상 속 구강 케어를 더 전문적으로 제안합니다.",
      "매일 사용하는 제품일수록 더 꼼꼼하게, 더 신뢰할 수 있게. 건강한 미소를 위한 새로운 기준, 닥터바이트.",
    ],
    heroImage: "/images/brands/drbite_hero.jpg",
    cardImage: "/images/brands/drbite-card.jpg",
    storeUrl: "https://drbite.kr/",
    isActive: true,
  },
    {
    slug: "elikorea",
    name: "일라이코리아",
    nameEn: "Eli Korea",
    category: "TODO",
    tagline: "일상의 흐름을 일라이 코리아와 함께 개선하세요",
    story: [
      "일라이 코리아는 더 나은 일상을 위한 변화를 고민합니다.",
      "매일 반복되는 순간을 조금 더 편안하게, 익숙한 생활에 새로운 기준과 가치를 더합니다.",
      "작은 변화가 더 좋은 하루로 이어질 수 있도록 일라이 코리아가 당신의 일상과 함께합니다.",
    ],
    heroImage: "/images/brands/elikorea_hero.jpg",
    cardImage: "/images/brands/dodit-card.jpg",
    storeUrl: "https://elikorea.kr/",
    products: [
      { image: "/images/brands/elikorea_prod_1.jpg", link: "https://elikorea.kr/products/?idx=6" },
      { image: "/images/brands/elikorea_prod_2.jpg", link: "https://elikorea.kr/products/?idx=7" },
    ],
    isActive: true,
  },
  {
    slug: "kidzdam",
    name: "키즈담",
    nameEn: "KiDZ:DAM",
    category: "TODO",
    tagline: "아이의 오늘을 채우고, 내일의 성장을 담다",
    story: [
      "키즈담은 아이의 키 성장부터 두뇌 건강까지, ",
      "부모가 안심하고 선택할 수 있는 제품을 연구하고 제안합니다.",
      "아이의 가능성이 더 크게 자랄 수 있도록, 성장에 필요한 좋은 것들을 차곡차곡 담습니다.",
    ],
    heroImage: "/images/brands/kidzdam_hero.jpg",
    cardImage: "/images/brands/kidzdam-card.jpg",
    storeUrl: "https://kidzdam.kr/products",
      products: [
      { image: "/images/brands/kidzdam_prod_1.jpg", link: "https://kidzdam.kr/products/?idx=4" },
      { image: "/images/brands/kidzdam_prod_2.jpg", link: "https://kidzdam.kr/products/?idx=6" },
    ],
    isActive: true,
  },
  {
    slug: "kidzplan",
    name: "키즈플랜",
    nameEn: "KIDZPLAN",
    category: "TODO",
    tagline: "아이의 성장을 위한 더 나은 기준, 키즈플랜",
    story: [
      "키즈플랜은 아이의 건강한 성장과 쾌적한 일상을 함께 고민하는 프리미엄 키즈 라이프케어 브랜드입니다.",
      "성장기 아이를 위한 영양 관리부터 아이와 함께하는 생활 공간까지,",
      "일상에 필요한 제품을 세심하게 제안합니다.",
      "성분과 품질을 꼼꼼하게 살피며 부모가 믿고 선택할 수 있는 기준을 만들어갑니다.",
      "건강하게 자라는 시간, 키즈플랜이 함께합니다.",
    ],
    heroImage: "/images/brands/kidzplan_hero.jpg",
    cardImage: "/images/brands/kidzplan-card.jpg",
    storeUrl: "https://kidzplan.kr",
    products: [
      { image: "/images/brands/kidzplan_prod_1.jpg", link: "https://kidzplan.kr/15/?idx=1" },
      { image: "/images/brands/kidzplan_prod_2.jpg", link: "https://kidzplan.kr/15/?idx=11" },
    ],
    isActive: true,
  },
  {
    slug: "livature",
    name: "리브어쳐",
    nameEn: "Livature",
    category: "TODO",
    tagline: "수년간의 연구를 거쳐 생산된\n 풍성함을 위한 유일한 선택지",
    story: [
      "풍성함의 시작부터 꾸준한 관리까지.",
      "모발과 두피의 변화를 세심하게 바라보고 근거 있는 성분과 전문적인 솔루션을 제안합니다.",
      "매일 이어지는 관리가 더 나은 변화로 이어질 수 있도록 건강한 모발을 위한 새로운 기준을 만들어갑니다.",
    ],
    heroImage: "/images/brands/livature_hero.jpg",
    cardImage: "/images/brands/livature-card.jpg",
    storeUrl: "https://livature.kr/",
    products: [
      { image: "/images/brands/livature_prod_1.jpg", link: "https://livature.kr/Product/?idx=3" },
    ],
    isActive: true,
  },
  {
    slug: "livderm",
    name: "리브덤",
    nameEn: "LIVDERM",
    category: "TODO",
    tagline: "시간이 만든 변화까지 세심하게 케어하는 \n프리미엄 에이징 솔루션, 리브덤.",
    story: [
      "리브덤은 나이가 들며 달라지는 몸과 피부의 변화를 연구합니다.",
      "움직임이 신경 쓰이는 관절 부위에는 타마누 집중 케어를,",
      "탄력과 주름이 고민되는 눈가에는 섬세한 안티에이징 케어를 제안합니다.",
      "필요한 부위에 필요한 성분을 담아, 매일 꾸준히 사용할 수 있도록.",
      "리브덤은 건강하고 자신 있는 일상을 위한 전문적인 에이징 케어를 만듭니다.",
    ],
    heroImage: "/images/brands/livderm_hero.jpg",
    cardImage: "/images/brands/livderm-card.jpg",
    storeUrl: "https://livderm.kr",
    products: [
      { image: "/images/brands/livderm_prod_1.jpg", link: "https://livderm.kr/shop/?idx=6" },
      { image: "/images/brands/livderm_prod_2.jpg", link: "https://livderm.kr/shop/?idx=3" },
    ],
    isActive: true,
  },
  {
    slug: "moyoku",
    name: "모요쿠",
    nameEn: "MOYOKU",
    category: "TODO",
    tagline: "일상의 피로를 씻어내고\n행복한 순간을 선물합니다.",
    story: [
      "모요쿠는 목욕을 단순한 휴식이 아닌, 몸과 마음을 회복하는 하나의 루틴으로 바라봅니다.",
      "하루의 피로를 부드럽게 씻어내고, 기능성 목욕이 주는 깊은 편안함을 일상에 더합니다.",
      "매일의 끝을 조금 더 행복하게, 모요쿠.",
    ],
    heroImage: "/images/brands/moyoku_hero.jpg",
    cardImage: "/images/brands/moyoku-card.jpg",
    storeUrl: "https://moyoku.kr/",
    products: [
      { image: "/images/brands/moyoku_prod_1.jpg", link: "https://moyoku.kr/Products/?idx=7" },
      { image: "/images/brands/moyoku_prod_2.jpg", link: "https://moyoku.kr/Products/?idx=8" },
    ],
    isActive: true,
  },
  {
    slug: "oroshe",
    name: "오로쉬",
    nameEn: "Oroshe",
    category: "TODO",
    tagline: "새로운 시작을 위한 루틴,\n 함께를 위한 한 알",
    story: [
      "오로쉬는 여성의 몸이 보내는 작은 변화에 귀 기울입니다.",
      "지금의 건강이 앞으로의 삶과 자연스럽게 이어질 수 있도록,",
      "여성에게 필요한 균형과 건강한 일상을 연구합니다.",
      "준비하는 순간부터 새로운 시작을 맞이하는 시간까지,",
      "오로쉬는 여성의 모든 변화 곁에 함께합니다.",
    ],
    heroImage: "/images/brands/oroshe_hero.jpg",
    cardImage: "/images/brands/oroshe-card.jpg",
    storeUrl: "https://oroshe.kr",
    // instagramUrl: "https://instagram.com/oroshe",
        products: [
      { image: "/images/brands/oroshe_prod_1.jpg", link: "https://oroshe.kr/product/?idx=3" },
    ],
    isActive: true,
  },
  {
    slug: "planlight",
    name: "플랜라이트",
    nameEn: "Planlight",
    category: "TODO",
    tagline: "가볍게 만드는 일에 집중합니다",
    story: [
      "가벼워지고 싶은 여성의 일상을 연구합니다.",
      "일본에서 사랑받아 온 섬세한 다이어트 설계로, 무리하지 않고 꾸준히 이어가는 건강한 습관을 제안합니다.",
      "매일의 나를 더 가볍게, 플랜라이트.",
    ],
    heroImage: "/images/brands/planlignt_hero.jpg",
    cardImage: "/images/brands/planlight-card.jpg",
    storeUrl: "https://planlight.co.kr/", 
    products: [
      { image: "/images/brands/planlight_prod_1.jpg", link: "https://planlight.co.kr/shop_view/?idx=4" },
    ],
    isActive: true,
  },
];
